### ISSUE TITLE
"setNativeProps is deprecated. Please update props using React state instead." warning on react native

### ISSUE THREAD

**Issue by daniel-230a** [react-community/react-navigation#11137]
### Current behavior

![error ](https://user-images.githubusercontent.com/73724840/210764699-a35dbd4b-0c20-4df6-bd98-3471288121b9.png)
![error 2](https://user-images.githubusercontent.com/73724840/210764719-2155f1ea-67dd-4cbf-bdb2-13b5413d8724.png)

The warning "setNativeProps is deprecated. Please update props using React state instead." is shown even on production on the console. 

I haven't tested other types of navigation but at the moment I'm using the bottom tab navigation for my project.

I looked at the snack for the official documentation of tab-based navigation and I also saw the warning log there. (also shown in picture)
Link: https://reactnavigation.org/docs/tab-based-navigation#minimal-example-of-tab-based-navigation
 
I have tested this on both google chrome and Edge browsers

### Expected behavior

No deprecation warning log shown

### Reproduction

https://snack.expo.dev/@daniel_230a/bottomtabnav---react-navigation

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native                |  "^6.1.1"
| @react-navigation/bottom-tabs      | "^6.5.2"
| @react-navigation/native-stack       | "^6.9.7"
| react-native-safe-area-context         | "4.4.1"
| react-native-screens                         | "~3.18.0"
| react-native                                      | "0.70.5"
| expo                                                 | "^47.0.0"
| node                                                 | v16.13.1
| yarn                                                  | v1.22.19

**Comment by markjsc** [comment]
For what it's worth, I'm seeing the same warning, although I'm not using expo or react-native-tab-view.

Here's my warning stack:
`react_devtools_backend.js:4012
setNativeProps is deprecated. Please update props using React state instead. 
    at Card (http://localhost:3000/static/js/bundle.js:133257:5)
    at CardContainer (http://localhost:3000/static/js/bundle.js:133722:5)
    at div
    at http://localhost:3000/static/js/bundle.js:266943:25
    at WebScreen (http://localhost:3000/static/js/bundle.js:133105:1)
    at AnimatedComponent (http://localhost:3000/static/js/bundle.js:275064:7)
    at AnimatedComponentWrapper
    at MaybeScreen (http://localhost:3000/static/js/bundle.js:133142:5)
    at div
    at http://localhost:3000/static/js/bundle.js:266943:25
    at MaybeScreenContainer (http://localhost:3000/static/js/bundle.js:133126:5)
    at CardStack (http://localhost:3000/static/js/bundle.js:134170:5)
    at KeyboardManager (http://localhost:3000/static/js/bundle.js:132901:5)
    at div
    at http://localhost:3000/static/js/bundle.js:266943:25
    at NativeSafeAreaProvider (http://localhost:3000/static/js/bundle.js:258473:5)
    at SafeAreaProvider (http://localhost:3000/static/js/bundle.js:258633:5)
    at SafeAreaProviderCompat (http://localhost:3000/static/js/bundle.js:133045:5)
    at div
    at http://localhost:3000/static/js/bundle.js:266943:25
    at StackView (http://localhost:3000/static/js/bundle.js:134586:5)
    at StackNavigator (http://localhost:3000/static/js/bundle.js:131637:5)
    at EnsureSingleNavigator (http://localhost:3000/static/js/bundle.js:124974:5)
    at BaseNavigationContainer (http://localhost:3000/static/js/bundle.js:124674:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:128988:5)
    at NavigationContainer (http://localhost:3000/static/js/bundle.js:128699:5)
    at Navigator (http://localhost:3000/static/js/bundle.js:63454:52)
    at RecertificationProvider (http://localhost:3000/static/js/bundle.js:49817:5)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:24569:1)
    at MainProvider (http://localhost:3000/static/js/bundle.js:49327:5)
    at AuthProvider (http://localhost:3000/static/js/bundle.js:45363:5)
    at AppProvider (http://localhost:3000/static/js/bundle.js:45152:5)
    at App (http://localhost:3000/static/js/bundle.js:3015:51)
    at AppWrapper`

Navigator is our last custom component - everything above that is abstracted in packages.

Here are some of the relevant package versions:
"@react-navigation/native": "5.9.8",
"@react-navigation/stack": "5.14.9",
"react-native": "0.70.7",

node: 16.15.0
yarn: 3.3.0

**Comment by kirtikapadiya** [comment]
I think react native team will try to fix it -https://medium.com/@david.zhao.blog/setnativeprops-is-deprecated-please-update-props-using-react-state-instead-7d5b17e4c197

**Comment by EOMZON** [comment]
I met the same question, who know how to fix it?

"setNativeProps is deprecated. Please update props using React state instead."

**Comment by danielChuks** [comment]
Has there been any solution provided on this issue

**Comment by markjsc** [comment]
> Has there been any solution provided on this issue

I'm still seeing it. My current versions are:
"@react-navigation/native": "6.1.6",
"@react-navigation/stack": "6.3.16",
"react-native": "0.71.4",

node: 18.15.0
yarn: 3.3.0

**Comment by skizzo** [comment]
+1
