### ISSUE TITLE
Can't test with jest – Cannot access property AppNavigator from undefined

### ISSUE THREAD

**Issue by jsdario** [react-community/react-navigation#1183]
Hi,

I just migrated from ex-navigation where all my tests worked. I followed the guides, and read the docs. The app is completely functional, but I need to get the tests working. Everything looks just fine, but the error won't let me run none of my tests. Seems to be an error on transpile time, where the module is undefined. However I cannot even log the value of the imported packages.

![screen shot 2017-04-23 at 17 00 00](https://cloud.githubusercontent.com/assets/5166506/25314535/52df02c4-2846-11e7-83c0-e5c2b0c1eeff.png)

[I also created a question for this matter on Stackoverflow.](http://stackoverflow.com/questions/43572745/cannot-read-exported-module-on-jest-react-navigation)

This is the code that throws:

```
import { AppNavigator } from '../AppNavigator'

/*
** navigation
*/
export function navigation (state, action) {
  const nextState = AppNavigator.router.getStateForAction(action, state)
  return { ...state, ...nextState}
}
```

This is how I export AppNavigator:
```
/**
* @providesModule %AppNavigator
* @flow
*/
import {
  StackNavigator,
} from 'react-navigation'

import { CloudAccount } from './containers/integrations/CloudAccount'
import * as Containers from './containers'

const routes = {
  Init: {
    screen: Containers.Init,
  },
  CloudAccount: {
    screen: CloudAccount,
  },
}

Object.keys(Containers).forEach(key => {
  routes[key] = {
    screen: Containers[key],
  }
})

export const AppNavigator = StackNavigator(routes, {
  headerMode: 'screen',
  navigationOptions: {
    gesturesEnabled: false,
    headerStyle: {
      backgroundColor: 'white',
      elevation: 1,
    },
    headerTitleStyle: {
      alignSelf: 'center',
    },
    headerBackTitle: null,
  },
  cardStyle: {
    backgroundColor: 'white',
  },
})

```

This is my jest config:
```
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation)"
    ],
    "collectCoverageFrom": [
      "app/**/*.{js,jsx}",
      "!**/node_modules/**",
      "!**/tasks/**",
      "!**/meta/**",
      "!**/ios/**",
      "!**/app/lib/**"
    ],
    "coverageDirectory": "meta/coverage",
    "testEnvironment": "jsdom",
    "moduleNameMapper": {
      "^React$": "<rootDir>/node_modules/react"
    }
  },
```

I already removed node_modules, reinstalled, removed watchman and cleaned cachés. Does anyone have a clue?

More:
```
React Native 0.43 (I need FlatList)
Jest 0.19
Node v7
```

**Comment by AlanFoster** [comment]
@jsdario Nothing springs to mind immediately. I believe you can remove `@providesModule %AppNavigator` though?

What does your failing test look like?

**Comment by jsdario** [comment]
Up there is a picture on how the test looks like. I tried modyfing in many ways how the `AppNavigator` is exported. However, it does not seem the problem, will have a similar problem if I just change imports order, but with a different module.

**Comment by grabbou** [comment]
Are you sure `jest` is not auto-mocking these files?

**Comment by jsdario** [comment]
No, how would it affect in anyway? And, how can I prevent `jest` from doing such thing?

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by medmo7** [comment]
Please can any one be kind enough and provide a clear example on how to deal with react-navigation when testing with jest:
 - Do we have to create a manual mock for it in __mocks__ folder? if yes an example would be great.
I get this error when testing:

```
Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. The wrapped component is unable to get access to navigation from props or context.

      at React (node_modules/@react-navigation/core/lib/commonjs/utils/invariant.js:45:11)
      at node_modules/@react-navigation/core/lib/commonjs/views/withNavigation.js:10:41
      at updateContextConsumer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7275:19)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7441:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10138:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10170:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10256:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11121:7)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11033:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11007:3)


  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8060
    The above error occurred in the <Context.Consumer> component:
        in withNavigation(NavigationEvents) (at Settings.js:116)
        in View (created by View)
        in View (at ScrollViewMock.js:29)
        in RCTScrollView (created by _class)
        in _class (at ScrollViewMock.js:27)
        in ScrollViewMock (at Settings.js:112)
        in Settings (at setting.test.js:22)
```
**Thanks!**
