### ISSUE TITLE
How to add ToolbarActions on Header

### ISSUE THREAD

**Issue by maggialejandro** [react-community/react-navigation#1212]
Hi, I need to add some sort of Dropdown Menu in the Header.
Something like toolbarAction on [ToolbarAndroid](https://facebook.github.io/react-native/docs/toolbarandroid.html).

This is the [UX](https://material.io/guidelines/components/menus.html#menus-usage) that I want to implement.

<img width="360" alt="components_menus_usage2" src="https://cloud.githubusercontent.com/assets/3394748/25347849/a272cac6-28f2-11e7-9626-e1b15e2c3340.png">
<img width="360" alt="components_menus_usage2" src="https://cloud.githubusercontent.com/assets/3394748/25347850/a2950960-28f2-11e7-910a-94c3464a99b4.png">

is it possible?
Thanks in advance

**Comment by cyprusglobe** [comment]
You might have to pair with using this
```
https://github.com/jaysoo/react-native-menu
```

**Comment by grabbou** [comment]
You can use `headerRight` (https://reactnavigation.org/docs/navigators/stack#headerRight) to render your custom menu component.

**Comment by maggialejandro** [comment]
I was able to implement a Dropdown menu using **UIManager.showPopupMenu**
labels is an Array of Strings.
The code looks like this:
```javascript
  import React, { Component } from 'react';
  import { View, StyleSheet, NativeModules, findNodeHandle } from 'react-native';
  import MaterialIcons from 'react-native-vector-icons/MaterialIcons';

  import styles from './styles';

  const UIManager = NativeModules.UIManager;

  export default class ToolbarDropdown extends Component {
    onMenuPressed = (labels) => {
      const { onPress } = this.props;

      UIManager.showPopupMenu(
        findNodeHandle(this.menu),
        labels,
        () => {},
        (result, index) => {
          if (onPress) {
            onPress({ action: 'menu', result, index });
          }
        },
      );
    };

    render() {
      const { labels } = this.props;

      return (
        <View style={{flexDirection: 'row'}}>
          <View>
            <View
              ref={c => this.menu = c}
              style={{
                backgroundColor: 'transparent',
                width: 1,
                height: StyleSheet.hairlineWidth,
              }}
            />
            <MaterialIcons
              name="more-vert"
              onPress={() => this.onMenuPressed(labels)}
              style={{ marginRight: 10, color: 'white' }}
              size={30}
            />
          </View>
        </View>
      )
    }
  }
```

**Comment by archanasantoshwhatkar** [comment]
At my side its not working, I need same dropdown as above.
pls guide. 
Thank you

**Comment by lironsher** [comment]
Hi,
I've used this dropdown - https://github.com/sohobloo/react-native-modal-dropdown
and add it as : headerRight.
`<ModalDropdown 
    textStyle={styles.dropDownTextBtn} 
    dropdownTextStyle={styles.dropDownTextBtn} 
    defaultValue = {navigation.state.params.name}
    options={['English', 'Hebrew']}
    />`

**Comment by archanasantoshwhatkar** [comment]
Hello Lironsher,
<img width="152" alt="screen shot 2018-01-16 at 10 05 11 pm" src="https://user-images.githubusercontent.com/32349284/34992844-702c3eaa-fb09-11e7-8f93-bd2cad777596.png">
 if I want to show like above dropdown list do you know how to do it?

Thanks in advance.

**Comment by ZeroCool00** [comment]
@archanasantoshwhatkar  any luck yet?

**Comment by pulpdood** [comment]
I've created a fork which supports using a custom button: https://github.com/pulpdood/react-native-modal-dropdown

To use simply add this to your package.json: 
    "react-native-modal-dropdown": "pulpdood/react-native-modal-dropdown.git",

I then use this code to emulate the menu button:
```javascript
MainStack = createStackNavigator({
   MainScreen: {
     screen: MainTabNavigator,
     navigationOptions: { 
		title: 'App',
		headerRight: (	<ModalDropdown options={menuArray} 
			dropdownStyle={{height: 40 * menuArray.length, alignItems: 'center'}} 
			dropdownTextStyle={{fontSize: 16, color: 'black'}}
			textStyle={{fontSize: 30, marginRight: 5, color: 'black'}}
			customButton="⋮"
			 />  ),
	},
    }
});
```

`textStyle={{fontSize: 30, marginRight: 5, color: 'black'}}`
^ I find this setting best for rendering the three dot menu symbol

`customButton="⋮"`
^ This overrides the text of the button to be what we want

Any issues please let me know

**Comment by cassioseffrin** [comment]
The @maggialejandro approach < UIManager.showPopupMenu(...) > is causing a crash in android 4.4 (sdk 19). All tests above sdk 19  are fine.

Although it isn't in oficial docs of RN, the UIManager is the best option for performance reasons.  But also there is a nice option here: https://github.com/instea/react-native-popup-menu 

My Env:
 ```
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
```
 My log from adb logcat E:* is : 
```
E/unknown:ReactNative( 2145): Exception in native call
E/unknown:ReactNative( 2145): java.lang.NullPointerException
E/unknown:ReactNative( 2145): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.showPopupMenu(NativeViewHierarchyManager.java:795)
E/unknown:ReactNative( 2145): 	at com.facebook.react.uimanager.UIViewOperationQueue$ShowPopupMenuOperation.execute(UIViewOperationQueue.java:334)
E/unknown:ReactNative( 2145): 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:844)
E/unknown:ReactNative( 2145): 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:952)
E/unknown:ReactNative( 2145): 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:44)
E/unknown:ReactNative( 2145): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1012)
E/unknown:ReactNative( 2145): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
E/unknown:ReactNative( 2145): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
E/unknown:ReactNative( 2145): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/unknown:ReactNative( 2145): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
E/unknown:ReactNative( 2145): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/unknown:ReactNative( 2145): 	at android.view.Choreographer.doFrame(Choreographer.java:543)
E/unknown:ReactNative( 2145): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/unknown:ReactNative( 2145): 	at android.os.Handler.handleCallback(Handler.java:733)
E/unknown:ReactNative( 2145): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:ReactNative( 2145): 	at android.os.Looper.loop(Looper.java:136)
E/unknown:ReactNative( 2145): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/unknown:ReactNative( 2145): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:ReactNative( 2145): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:ReactNative( 2145): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/unknown:ReactNative( 2145): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/unknown:ReactNative( 2145): 	at dalvik.system.NativeStart.main(Native Method)
E/EGL_emulation( 2145): tid 2145: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
```
Any help for solve android 4.4 issue will be appreciated.

**Comment by cassioseffrin** [comment]
@archanasantoshwhatkar @ZeroCool00 take a look at https://github.com/instea/react-native-popup-menu
