### ISSUE TITLE
NavigationPlayground react-native run-ios SyntaxError

### ISSUE THREAD

**Issue by FrankSalad** [react-community/react-navigation#1457]
`$ git clone` repo at d4b4697f338c5d5673c7a155cd7601d62a9eebc2
`$ cd react-navigation/examples/NavigationPlayground`
`$yarn`
... ✨  Done
`$ react-native run-ios`

```
./react-navigation/rn-cli.config.js:20
    ...config.getBlacklistForExample(example),
    ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (./react-navigation/examples/NavigationPlayground/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.get (./react-navigation/examples/NavigationPlayground/node_modules/react-native/local-cli/util/Config.js:53:9)
    at getCliConfig (./react-navigation/examples/NavigationPlayground/node_modules/react-native/local-cli/core/index.js:96:17)
```

**Comment by ryancoughlin** [comment]
Getting something similar as well, following the same steps above.

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'react-native/packager/blacklist'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ryancoughlin/Downloads/react-navigation-master/rn-cli.config.js:10:19)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ryancoughlin/Downloads/react-navigation-master/examples/NavigationPlayground/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by spencercarli** [comment]
You want to use `npm run ios` instead
