### ISSUE TITLE
 SyntxError in createNavigationContainer.js

### ISSUE THREAD

**Issue by xuechaow** [react-community/react-navigation#1594]
While compiling using gulp, got SyntxError

### Current Behavior
```
/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^
SyntaxError: /Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-navigation/src/createNavigationContainer.js: Unexpected token (20:19)
  18 |   uriPrefix?: string,
  19 |   onNavigationStateChange?: (
> 20 |     NavigationState,
     |                    ^
  21 |     NavigationState,
  22 |     NavigationAction,
  23 |   ) => void,
    at Parser.pp.raise (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.expect (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/parser/util.js:83:33)
    at Parser.pp.flowParsePrimaryType (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/plugins/flow.js:927:14)
    at Parser.pp.flowParsePostfixType (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/plugins/flow.js:991:38)
    at Parser.pp.flowParsePrefixType (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/plugins/flow.js:1007:17)
    at Parser.pp.flowParseIntersectionType (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/plugins/flow.js:1013:19)
    at Parser.pp.flowParseUnionType (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/plugins/flow.js:1023:19)
    at Parser.pp.flowParseType (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/plugins/flow.js:1034:19)
    at Parser.pp.flowParseTypeInitialiser (/Users/wxuecha/workspaces/ApiaryDev/src/ApiaryJavaScriptBundle/node_modules/react-native/node_modules/babylon/lib/plugins/flow.js:443:19)
```

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.26.3
| node             | v5.9.0
| npm or yarn      | 3.7.3

**Comment by matthamil** [comment]
Can you share more information about your gulp config?

**Comment by xuandiboss** [comment]
I have the same problem, but I use `react-native start` command to start and the version of react-native is 0.30.0

**Comment by MarkTangs** [comment]
I also encountered the same problem

**Comment by skovhus** [comment]
Might be related to https://github.com/react-community/react-navigation/issues/2207

**Comment by kelset** [comment]
Pinging OP @xuechaow since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @xuechaow ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
