### ISSUE TITLE
Error when running the example.

### ISSUE THREAD

**Issue by eric-PearSports** [react-community/react-navigation#1629]
Running the example, on running "npm run run-playground-ios".
Example ran from:
https://reactnavigation.org/docs/guides/contributors

I get the following error:
4:56:18 PM: Error: './assets/icons/react-navigation.png' could not be found, because './assets/icons' is not a subdirectory of any of the roots  ('/Users/eric/Projects/GitHub/react-navigation')
    at Promise.all.then.stats (/Users/eric/Projects/GitHub/react-navigation/examples/NavigationPlayground/node_modules/react-native/packager/src/AssetServer/index.js:181:13)

4:56:18 PM: Failed building JavaScript bundle
4:56:19 PM: Error: './assets/icons/react-navigation.png' could not be found, because './assets/icons' is not a subdirectory of any of the roots  ('/Users/eric/Projects/GitHub/react-navigation')
    at Promise.all.then.stats (/Users/eric/Projects/GitHub/react-navigation/examples/NavigationPlayground/node_modules/react-native/packager/src/AssetServer/index.js:181:13)

**Comment by janreyho** [comment]
+1

**Comment by spencercarli** [comment]
Consolidating NavigationPlayground related issues to #2170.
