### ISSUE TITLE
Jest failure with React Navigation

### ISSUE THREAD

**Issue by KevKo1990** [react-community/react-navigation#2024]
My problem is strongly related to the one mentioned here - however it is closed but I think there are still some problems left... https://github.com/react-community/react-navigation/issues/256

### Current Behavior
I'm working with react-native and when I run the basic index.android.js test file, it systematically fails.
I am not able to create any Snapshots... my error message:
```

    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

  ● renders correctly

    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
      
      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (node_modules/react-test-renderer/lib/instantiateReactComponent.js:77:56)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:367:22)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at mountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:55:31)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
```

### Expected Behavior
Expectation is that snapshots should be createable, I furthermore followed the recommendations from the issue above.

### My Environment
Ubuntu 16.4, x64

| software         | version
| ---------------- | -------
"react-navigation" | "^1.0.0-beta.11"
"react-native" | "0.44.3",
node | v6.10.1
yarn | 0.24.6

**Comment by elliotleelewis** [comment]
I get a very similar error message when just running a very basic Jest Test...

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `DrawerNavigatorItems`.

    at invariant (C:\Users\1219763\Projects\phoenix-mobile\node_modules\fbjs\lib\invariant.js:44:15)
    at createFiberFromElementType (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:1855:5)
    at createFiberFromElement (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:1800:15)
    at reconcileSingleElement (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:3172:19)
    at reconcileChildFibers (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:3282:37)
    at reconcileChildrenAtPriority (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:3915:30)
    at reconcileChildren (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:3903:5)
    at updateHostComponent (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:4173:7)
    at beginWork (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:4436:16)
    at performUnitOfWork (C:\Users\1219763\Projects\phoenix-mobile\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:6030:16)
```

**Comment by jkomyno** [comment]
Same. It seems that every time I run a snapshot test with Jest, all my components are evaluated to `undefined`. (Checked that by console.log'ing them).
I've even tried the following, without success

```javascript
jest.unmock('source/to/my/components');

// ... snapshot render stuff
```

**Comment by jkomyno** [comment]
It's worth saying that without the navigation logic, jest snapshots work perfectly.

**Comment by kelset** [comment]
Pinging OP @KevKo1990 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @KevKo1990 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by thevikas** [comment]
Im getting this error. Any ideas on why it happens and how to fix?

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
