### ISSUE TITLE
Syntax error for Flow type with 1.0.0-beta.12

### ISSUE THREAD

**Issue by ne8il** [react-community/react-navigation#2207]
Bundling for ios using 1.0.0-beta.12 gives me a syntax error for the spread operator in a flow type:

```
error: bundling: SyntaxError: /Users/neil/gitprojects/structural_ios/node_modules/react-navigation/src/views/CardStack/Card.js: Unexpected token (12:2)
  10 |
  11 | type Props = {
> 12 |   ...$Exact<NavigationSceneRendererProps>,
     |   ^
  13 |   children: React.Children<*>,
  14 |   onComponentRef: (ref: React.Element<*>) => void,
  15 |   pointerEvents: string,
    at Parser.pp$5.raise (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:4373:13)
    at Parser.pp.unexpected (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:1716:8)
    at Parser.pp$3.parseIdentifier (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:4251:10)
    at Parser.pp$8.flowParseObjectPropertyKey (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:5169:90)
    at Parser.pp$8.flowParseObjectType (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:5283:26)
    at Parser.pp$8.flowParsePrimaryType (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:5462:19)
    at Parser.pp$8.flowParsePostfixType (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:5580:19)
    at Parser.pp$8.flowParsePrefixType (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:5597:17)
    at Parser.pp$8.flowParseAnonFunctionWithoutParens (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:5602:20)
    at Parser.pp$8.flowParseIntersectionType (/Users/neil/gitprojects/structural_ios/node_modules/babylon/lib/index.js:5617:19)
Bundling `index.ios.js`  99.7% (2124/2130), failed.
```

I'm guessing I need to upgrade some other library or babel-plugin but not sure where to look.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     |  0.43.0-rc.4
| node             | v6.6.0
| yarn      | 0.27.5

**Comment by xiaohangsu** [comment]
+1

**Comment by lyingd** [comment]
+1

**Comment by skovhus** [comment]
@spencercarli @exKAZUu

I would like to help here, as I'm having the same issue. Any idea what causes this problem?

**Comment by skovhus** [comment]
To me the issue seems to be that consumer are getting the `src/*` and not the `lib/*` folder.

This is due to `"main": "src/react-navigation.js"` in package.json... https://github.com/react-community/react-navigation/blob/master/package.json#L5

Not sure why this isn't linking to `lib/react-navigation.js`

**Comment by spencercarli** [comment]
Flow has been revamped in 1.0.0-beta.16.
