### ISSUE TITLE
problem in import react-navigation

### ISSUE THREAD

**Issue by Sunshine168** [react-community/react-navigation#227]
i have a problem  when using  npm or cnpm to build the project 
i use the 
`react-native init AwesomeProject  
 npm install --save react-navigation`

and try 
> [Hello Mobile Navigation](https://reactnavigation.org/docs/intro/)
> [the device tips the issues 4968 in react-native ](https://github.com/facebook/react-native/issues/4968)

after i following those step  

it show me in terminal 
>Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined

and those info in device
![image](https://cloud.githubusercontent.com/assets/15126380/22721310/df32ab68-edea-11e6-8a12-9c856cc129e5.png)

finally i solve this problem  by using yarn ,may be some problem in the module part ?    
it cost me many time so i hope to get the problem  why?

**Comment by grabbou** [comment]
Is it possible you package your app and upload it somewhere so we can reproduce? I haven't experienced such problems before, might be just dependency issue or some packager problem, especially that you have mentioned `yarn` being a fix.

**Comment by Sunshine168** [comment]
i do not upload somewhere   maybe somewhere i ignore?   
well  i  list the detail for the mistake ,if it be necessary  , hoping then may help you reproduce ,
or just a tips for other if having same condition  

```
 Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
    at Client.connect (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.1.9.2@fb-watchman/index.js:184:14)
    at Client.command (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.1.9.2@fb-watchman/index.js:229:12)
    at Client.capabilityCheck (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.1.9.2@fb-watchman/index.js:291:8)
    at WatchmanWatcher.init (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.1.4.1@sane/src/watchman_watcher.js:173:15)
    at new WatchmanWatcher (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.1.4.1@sane/src/watchman_watcher.js:40:8)
    at createWatcher (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.18.0.0@jest-haste-map/build/index.js:536:23)
    at Array.map (native)
    at HasteMap._watch (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.18.0.0@jest-haste-map/build/index.js:654:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/MacBook/Documents/react/react-native/backup/AwesomeProject/node_modules/.18.0.0@jest-haste-map/build/index.js:250:21)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

packjson
```
{
	"name": "SimpleApp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"leancloud-storage": "^2.1.1",
		"react": "~15.4.0",
		"react-native": "0.42.0-rc.1",
		"react-navigation": "^1.0.0-beta.1"
	},
	"devDependencies": {
		"babel-jest": "18.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "18.1.0",
		"react-test-renderer": "~15.4.0"
	},
	"jest": {
		"preset": "react-native"
	}
}

```
