### ISSUE TITLE
Cannot Run iOS Example NavigationPlayground

### ISSUE THREAD

**Issue by tigarcia** [react-community/react-navigation#573]
I am trying to run NavigationPlayground on the iOS simulator and it is failing.

EXPECT:
An example app runs on my iOS simulator

ACTUAL:
Following the readme in the navigation playground directory, I receive the following error during `react-native start`:

```
React packager ready.

2017-03-04 11:20 node[5857] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-04 11:20 node[5857] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-04 11:20 node[5857] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-04 11:20 node[5857] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1012:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
```

I continue on with the instructions, then I get the following error during `react-native run-ios` while inside of the examples/NavigationPlayground directory:

```
React packager ready.

2017-03-04 11:23 node[6261] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-04 11:23 node[6261] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-04 11:23 node[6261] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1012:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
~
Process terminated. Press <enter> to close the window
```

Next, the navigation playground app starts up in the simulator, then dies immediately.

I'd like to help fix this but I'm not sure what the cause of the problem is.  Also, would it make sense to make `react-navigation` a dependency of the examples?  It seems like people looking at examples don't need to be on master.

**Comment by tigarcia** [comment]
Looks like it was my own problem. I had to update watchman to get this working.
