### ISSUE TITLE
Jest store provider error

### ISSUE THREAD

**Issue by JonFridrik** [react-community/react-navigation#699]
Hello everyone :)

I'm trying to test with jest but I am always getting the error:

```
Summary of all failing tests
 FAIL  __tests__/components/account/create-account/CreateAccount.test.js
  ● Test suite failed to run

    Invariant Violation: Route 'CREATE_ACCOUNT' should declare a screen. For example:

    import MyScreen from './MyScreen';
    ...
    CREATE_ACCOUNT: {
      screen: MyScreen,
    }

      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at node_modules/react-navigation/src/routers/validateRouteConfigMap.js:17:24
      at Array.forEach (native)
      at validateRouteConfigMap (node_modules/react-navigation/src/routers/validateRouteConfigMap.js:14:12)
      at Object.<anonymous>.exports.default (node_modules/react-navigation/src/routers/StackRouter.js:36:37)
      at Object.<anonymous>.exports.default (node_modules/react-navigation/src/navigators/StackNavigator.js:41:37)
      at Object.<anonymous> (js/navigation/AppNavigator.js:34:43)
```

My test looks like this:

```
import 'rxjs';
import React from 'react';
import renderer from 'react-test-renderer';
import { Provider } from 'react-redux';

import { PureCreateAccount } from '../../../../js/components/account/create-account';
import store from '../../../../js/reduxStore';

describe('Component CreateAccount', () => {
  test('renders correctly', () => {
    const tree = renderer.create(
      <Provider store={store}>
        <PureCreateAccount
          actions={{}}
          registerAccountPayoad={{}}
          userInfo={{}}
          navigation={{}}
        />
      </Provider>
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });
});

```
Can anyone help me with this error?

**Comment by ericvicenti** [comment]
Can you post the code for `PureCreateAccount` and `AppNavigator`, and re-open this issue? It is hard to see what is going wrong from your test code.

**Comment by eflath** [comment]
hey @JonFridrik any success with this? I am experiencing the same thing

**Comment by JonFridrik** [comment]
@eflath  I actually don't remember what I did to fix it. But it was some workaround.

The code is now like this:

`import 'rxjs';
import React from 'react';
import renderer from 'react-test-renderer';

import { PureCreateAccount } from '../../../../js/components/account/create-account';

jest.mock('../../../../js/components/account/create-account/TextboxFields', () => 'TextboxFields');
jest.mock('../../../../js/components/account/create-account/checkbox-fields', () => 'CheckboxFields');

describe('Component CreateAccount', () => {
  test('renders correctly', () => {
    const tree = renderer.create(
      <PureCreateAccount
        actions={{ resetUserInfo: () => {}, registerAccount: () => {} }}
        registerAccountPayload={{ error: false }}
        userInfo={{ password: '', externalSignup: false }}
        navigation={{ navigate: () => {}, goBack: () => {} }}
      />
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });
});
`

**Comment by cjlitch** [comment]
I'm also having this problem... Tried adding navigation props to my component but that didn't help.

**Comment by jkomyno** [comment]
For me it's the same as @cjlitch. If it can help, I am declaring two StackNavigator. Here's my AppNavigator.js:

```javascript
/**
 * @providesModule app/navigator
 */

import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import {
  addNavigationHelpers,
  StackNavigator,
} from 'react-navigation';
import { MenuHeaderRight } from 'app/components/toolbarmenu';

import {
  Activities,
  CompanyDetails,
  Login,
  Jobs,
  Projects,
  RDL,
  JobDetails,
  Settings,
} from 'app/screens';

const routesConfig = {
  Activities: {
    screen: Activities,
    navigationOptions: ({ navigation }) => ({
      title: 'Activities',
      headerRight: <MenuHeaderRight navigation={navigation} />,
    }),
  },
  Jobs: {
    screen: Jobs,
    navigationOptions: ({ navigation }) => ({
      title: 'Jobs',
      headerRight: <MenuHeaderRight navigation={navigation} />,
    }),
  },
  Projects: {
    screen: Projects,
    navigationOptions: ({ navigation }) => ({
      title: 'Projects',
      headerRight: <MenuHeaderRight navigation={navigation} />,
    }),
  },
  RDL: {
    screen: RDL,
    navigationOptions: {
      title: 'RDL',
    },
  },
  JobDetails: {
    screen: JobDetails,
    navigationOptions: {
      title: 'JOB Details',
    },
  },
  CompanyDetails: {
    screen: CompanyDetails,
    navigationOptions: ({ navigation }) => {
      const { description } = navigation.state.params.company;
      return {
        title: description,
      };
    },
  },
  Settings: {
    screen: Settings,
    navigationOptions: {
      title: 'Settings',
    },
  },
  Login: {
    screen: Login,
    navigationOptions: {
      header: null,
    },
  },
};

/**
 * Tests will fail here because I'm calling StackNavigator twice
 */

export const AppNavigator = StackNavigator(routesConfig, {
  initialRouteName: 'Jobs',
});

export const AppBeforeLogin = StackNavigator(routesConfig, {
  initialRouteName: 'Login',
});

export default class AppWithNavigationState extends PureComponent {

  static propTypes = {
    dispatch: PropTypes.func.isRequired,
    nav: PropTypes.object.isRequired,
  };

  render() {
    const {
      nav: state,
      ...otherProps
    } = this.props;

    return (
      <AppNavigator
        navigation={addNavigationHelpers({
          state,
          ...otherProps,
        })}
      />
    );
  }
}

```
